// Copyright (c) Suigar
// SPDX-License-Identifier: Apache-2.0

import type { SuiNetwork } from '../types/network.type.js';
import type { SuigarSettingsId } from '../types/suigar-config.type.js';
import {
	COINFLIP_SETTINGS_ID as MAINNET_COINFLIP_SETTINGS_ID,
	LIMBO_SETTINGS_ID as MAINNET_LIMBO_SETTINGS_ID,
	PLINKO_SETTINGS_ID as MAINNET_PLINKO_SETTINGS_ID,
	PVP_COINFLIP_SETTINGS_ID as MAINNET_PVP_COINFLIP_SETTINGS_ID,
	RANGE_SETTINGS_ID as MAINNET_RANGE_SETTINGS_ID,
	WHEEL_SETTINGS_ID as MAINNET_WHEEL_SETTINGS_ID,
} from './settings.mainnet.js';
import {
	COINFLIP_SETTINGS_ID as TESTNET_COINFLIP_SETTINGS_ID,
	LIMBO_SETTINGS_ID as TESTNET_LIMBO_SETTINGS_ID,
	PLINKO_SETTINGS_ID as TESTNET_PLINKO_SETTINGS_ID,
	PVP_COINFLIP_SETTINGS_ID as TESTNET_PVP_COINFLIP_SETTINGS_ID,
	RANGE_SETTINGS_ID as TESTNET_RANGE_SETTINGS_ID,
	WHEEL_SETTINGS_ID as TESTNET_WHEEL_SETTINGS_ID,
} from './settings.testnet.js';

export const SETTINGS_IDS: Record<SuiNetwork, SuigarSettingsId> = {
	mainnet: {
		coinflip: MAINNET_COINFLIP_SETTINGS_ID,
		limbo: MAINNET_LIMBO_SETTINGS_ID,
		plinko: MAINNET_PLINKO_SETTINGS_ID,
		pvpCoinflip: MAINNET_PVP_COINFLIP_SETTINGS_ID,
		range: MAINNET_RANGE_SETTINGS_ID,
		wheel: MAINNET_WHEEL_SETTINGS_ID,
	},
	testnet: {
		coinflip: TESTNET_COINFLIP_SETTINGS_ID,
		limbo: TESTNET_LIMBO_SETTINGS_ID,
		plinko: TESTNET_PLINKO_SETTINGS_ID,
		pvpCoinflip: TESTNET_PVP_COINFLIP_SETTINGS_ID,
		range: TESTNET_RANGE_SETTINGS_ID,
		wheel: TESTNET_WHEEL_SETTINGS_ID,
	},
};
