name: Turborepo

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/actions/setup-node-pnpm/action.yaml'
      - '.github/workflows/turborepo.yaml'
      - '.oxlintrc.json'
      - '.prettierignore'
      - '.prettierrc.json'
      - 'playground/**'
      - 'packages/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'tsconfig.shared.json'
      - 'turbo.json'
  pull_request:
    paths:
      - '.github/actions/setup-node-pnpm/action.yaml'
      - '.github/workflows/turborepo.yaml'
      - '.oxlintrc.json'
      - '.prettierignore'
      - '.prettierrc.json'
      - 'playground/**'
      - 'packages/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'tsconfig.shared.json'
      - 'turbo.json'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.0
        with:
          fetch-depth: 0

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          install: 'false'
          cache: 'false'

      - name: Run audit
        run: pnpm audit --prod --audit-level high

  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.0
        with:
          fetch-depth: 0

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Manypkg Check
        run: pnpm manypkg check

      - name: Lint packages
        run: pnpm turbo run lint --filter='./packages/*'

      - name: Lint Playground
        run: pnpm turbo run lint --filter='./playground'

      - name: Run packages tests
        run: pnpm turbo run test --filter='./packages/*'

      - name: Run packages typecheck
        run: pnpm turbo run typecheck --filter='./packages/*'

      - name: Run packages builds
        run: pnpm turbo run build:ci --filter='./packages/*'

      - name: Run Playground typecheck
        run: pnpm turbo run typecheck --filter='./playground'

      - name: Run Playground build
        run: pnpm turbo run build --filter='./playground'
